#!/usr/bin/env bash
# Stage 2: shared EQ pipeline + Spotify Connect + Bluetooth sink.
# Every source (AirPlay, Spotify, Bluetooth) plays through the "equal" ALSA device.
set -euo pipefail

EQ_STATE_DIR=/var/lib/alsaequal
AIRPLAY_NAME="${AIRPLAY_NAME:-Pi Speakers}"

install_packages() {
  apt-get install -y --no-install-recommends \
    libasound2-plugin-equal alsa-utils curl \
    bluez bluez-alsa-utils bluez-tools
  apt-get install -y --no-install-recommends pi-bluetooth || true
}

write_alsa_config() {
  cat > /etc/asound.conf <<'EOF'
# Shared pipeline: any source -> equalizer -> software mixer -> USB DAC.
pcm.dmixer {
  type dmix
  ipc_key 2048
  ipc_perm 0666
  slave {
    pcm "hw:CARD=Creation"
    rate 44100
    format S16_LE
    channels 2
    period_size 1024
    buffer_size 8192
  }
}

pcm.dmixed_plug {
  type plug
  slave.pcm "dmixer"
}

ctl.equal {
  type equal
  controls "/var/lib/alsaequal/controls"
}

pcm.equalizer {
  type equal
  slave.pcm "dmixed_plug"
  controls "/var/lib/alsaequal/controls"
}

pcm.equal {
  type plug
  slave.pcm "equalizer"
}

pcm.!default {
  type plug
  slave.pcm "equalizer"
}
EOF
}

seed_eq_state() {
  install -d -m 777 "$EQ_STATE_DIR"
  amixer -D equal scontrols >/dev/null
  chmod 666 "$EQ_STATE_DIR/controls"
}

verify_pipeline() {
  timeout 10 aplay -D equal -f S16_LE -c 2 -r 44100 -d 1 /dev/zero
}

configure_shairport() {
  cat > /etc/shairport-sync.conf <<EOF
// Generated by 02-audio-stack.sh - restart with: sudo systemctl restart shairport-sync
general =
{
  name = "$AIRPLAY_NAME";
  output_backend = "alsa";
};

alsa =
{
  output_device = "equal";
  mixer_control_name = "Speaker";
  mixer_device = "hw:CARD=Creation";
};

metadata =
{
  enabled = "yes";
  include_cover_art = "no";
  pipe_name = "/tmp/shairport-sync-metadata";
};
EOF
  systemctl restart shairport-sync
}

install_spotify_connect() {
  command -v librespot >/dev/null || curl -sL https://dtcooper.github.io/raspotify/install.sh | sh

  sed -i '/^# managed-by-setup/,$d' /etc/raspotify/conf
  cat >> /etc/raspotify/conf <<EOF
# managed-by-setup
LIBRESPOT_NAME="$AIRPLAY_NAME"
LIBRESPOT_DEVICE="equal"
LIBRESPOT_BITRATE="320"
LIBRESPOT_INITIAL_VOLUME="60"
LIBRESPOT_ONEVENT="/opt/pi-speakers/spotify-event.sh"
EOF

  mkdir -p /etc/systemd/system/raspotify.service.d
  cat > /etc/systemd/system/raspotify.service.d/override.conf <<'EOF'
[Service]
# raspotify ships ProtectSystem=strict; allow the EQ state + now-playing files
ReadWritePaths=/var/lib/alsaequal /run/pi-speakers
EOF

  systemctl daemon-reload
  systemctl restart raspotify
}

setup_bluetooth() {
  sed -i 's/^#*DiscoverableTimeout.*/DiscoverableTimeout = 0/' /etc/bluetooth/main.conf
  sed -i 's/^#*PairableTimeout.*/PairableTimeout = 0/' /etc/bluetooth/main.conf
  sed -i 's/^#*AutoEnable.*/AutoEnable=true/' /etc/bluetooth/main.conf

  mkdir -p /etc/systemd/system/bluealsa-aplay.service.d
  cat > /etc/systemd/system/bluealsa-aplay.service.d/override.conf <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/bin/bluealsa-aplay --pcm=equal
EOF

  cat > /etc/systemd/system/bt-agent.service <<'EOF'
[Unit]
Description=Bluetooth auto-pairing agent
After=bluetooth.service
Requires=bluetooth.service

[Service]
ExecStart=/usr/bin/bt-agent -c NoInputNoOutput
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

  cat > /etc/systemd/system/bt-discoverable.service <<EOF
[Unit]
Description=Make the speaker discoverable over Bluetooth
After=bluetooth.service bt-agent.service
Requires=bluetooth.service

[Service]
Type=oneshot
ExecStartPre=/usr/sbin/rfkill unblock bluetooth
ExecStart=/bin/sh -c 'for i in \$(seq 12); do bluetoothctl list | grep -q Controller && break; sleep 5; done; bluetoothctl power on && bluetoothctl system-alias "$AIRPLAY_NAME" && bluetoothctl pairable on && bluetoothctl discoverable on'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now bluealsa bluealsa-aplay bt-agent bt-discoverable
}

disable_power_saving() {
  apt-get install -y --no-install-recommends iw iputils-arping

  # a napping wifi radio misses broadcast ARP/mDNS - the Pi "disappears"
  # from devices whose cache expired while unicast traffic keeps working
  printf "[connection]\nwifi.powersave = 2\n" > /etc/NetworkManager/conf.d/wifi-powersave.conf
  iw dev wlan0 set power_save off 2>/dev/null || true

  cat > /etc/systemd/system/cpu-performance.service <<'UNIT'
[Unit]
Description=Pin the CPU governor to performance

[Service]
Type=oneshot
ExecStart=/bin/sh -c "for g in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance > $g; done"

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now cpu-performance

  # the USB DAC must never be power-managed
  grep -q usbcore.autosuspend /boot/firmware/cmdline.txt \
    || sed -i "1s/$/ usbcore.autosuspend=-1/" /boot/firmware/cmdline.txt
}

install_packages
write_alsa_config
seed_eq_state
verify_pipeline
configure_shairport
install_spotify_connect
setup_bluetooth
disable_power_saving

echo "Stage 2 done: EQ pipeline + Spotify Connect + Bluetooth active"
