#!/usr/bin/env bash
# Stage 2: shared EQ pipeline + Spotify Connect + Bluetooth sink.
# Every source (AirPlay, Spotify, Bluetooth) plays through the "equal" ALSA device.
set -euo pipefail

EQ_STATE_DIR=/var/lib/alsaequal
AIRPLAY_NAME="${AIRPLAY_NAME:-Pi Speakers}"
AUDIO_CARD="${AUDIO_CARD:-Creation}"

install_packages() {
  apt-get install -y --no-install-recommends \
    libasound2-plugin-equal alsa-utils curl \
    bluez bluez-alsa-utils bluez-tools
  apt-get install -y --no-install-recommends pi-bluetooth || true
}

write_alsa_config() {
  cat > /etc/asound.conf <<'EOF'
# Shared pipeline: any source -> equalizer -> software mixer -> USB DAC.
pcm.dmixer {
  type dmix
  ipc_key 2048
  ipc_perm 0666
  slave {
    pcm "hw:CARD=Creation"
    rate 44100
    format S16_LE
    channels 2
    period_size 1024
    buffer_size 8192
  }
}

pcm.dmixed_plug {
  type plug
  slave.pcm "dmixer"
}

ctl.equal {
  type equal
  controls "/var/lib/alsaequal/controls"
}

pcm.equalizer {
  type equal
  slave.pcm "dmixed_plug"
  controls "/var/lib/alsaequal/controls"
}

pcm.equal {
  type plug
  slave.pcm "equalizer"
}

pcm.!default {
  type plug
  slave.pcm "equalizer"
}
EOF
  sed -i "s/CARD=Creation/CARD=$AUDIO_CARD/" /etc/asound.conf
}

seed_eq_state() {
  install -d -m 777 "$EQ_STATE_DIR"
  amixer -D equal scontrols >/dev/null
  chmod 666 "$EQ_STATE_DIR/controls"
}

verify_pipeline() {
  # a timeout kill (124) is fine: bcm2835 plays the test but hangs in the
  # final drain - genuine config errors fail instantly with other codes
  timeout 10 aplay -D equal -f S16_LE -c 2 -r 44100 -d 1 /dev/zero || [ $? -eq 124 ]
}

configure_shairport() {
  # hardware volume only on the USB DAC; onboard audio uses software volume
  MIXER_LINES=""
  [ "$AUDIO_CARD" = "Creation" ] && MIXER_LINES='  mixer_control_name = "Speaker";
  mixer_device = "hw:CARD=Creation";'

  cat > /etc/shairport-sync.conf <<EOF
// Generated by 02-audio-stack.sh - restart with: sudo systemctl restart shairport-sync
general =
{
  name = "$AIRPLAY_NAME";
  output_backend = "alsa";
};

alsa =
{
  output_device = "equal";
$MIXER_LINES
};

metadata =
{
  enabled = "yes";
  include_cover_art = "no";
  pipe_name = "/tmp/shairport-sync-metadata";
};
EOF
  systemctl restart shairport-sync
}

install_spotify_connect() {
  command -v librespot >/dev/null || curl -sL https://dtcooper.github.io/raspotify/install.sh | sh

  sed -i '/^# managed-by-setup/,$d' /etc/raspotify/conf
  cat >> /etc/raspotify/conf <<EOF
# managed-by-setup
LIBRESPOT_NAME="$AIRPLAY_NAME"
LIBRESPOT_DEVICE="equal"
LIBRESPOT_BITRATE="320"
LIBRESPOT_INITIAL_VOLUME="60"
LIBRESPOT_ONEVENT="/opt/pi-speakers/spotify-event.sh"
EOF

  mkdir -p /etc/systemd/system/raspotify.service.d
  cat > /etc/systemd/system/raspotify.service.d/override.conf <<'EOF'
[Service]
# raspotify ships ProtectSystem=strict; allow the EQ state + now-playing files
ReadWritePaths=/var/lib/alsaequal /run/pi-speakers
EOF

  systemctl daemon-reload
  systemctl restart raspotify
}

setup_bluetooth() {
  sed -i 's/^#*DiscoverableTimeout.*/DiscoverableTimeout = 0/' /etc/bluetooth/main.conf
  sed -i 's/^#*PairableTimeout.*/PairableTimeout = 0/' /etc/bluetooth/main.conf
  sed -i 's/^#*AutoEnable.*/AutoEnable=true/' /etc/bluetooth/main.conf

  mkdir -p /etc/systemd/system/bluealsa-aplay.service.d
  cat > /etc/systemd/system/bluealsa-aplay.service.d/override.conf <<'EOF'
[Service]
ExecStart=
ExecStart=/usr/bin/bluealsa-aplay --pcm=equal
EOF

  cat > /etc/systemd/system/bt-agent.service <<'EOF'
[Unit]
Description=Bluetooth auto-pairing agent
After=bluetooth.service
Requires=bluetooth.service

[Service]
ExecStart=/usr/bin/bt-agent -c NoInputNoOutput
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

  cat > /etc/systemd/system/bt-discoverable.service <<EOF
[Unit]
Description=Make the speaker discoverable over Bluetooth
After=bluetooth.service bt-agent.service
Requires=bluetooth.service

[Service]
Type=oneshot
ExecStartPre=/usr/sbin/rfkill unblock bluetooth
ExecStart=/bin/sh -c 'for i in \$(seq 12); do bluetoothctl list | grep -q Controller && break; sleep 5; done; bluetoothctl power on && bluetoothctl system-alias "$AIRPLAY_NAME" && bluetoothctl pairable on && bluetoothctl discoverable on'
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now bluealsa bluealsa-aplay bt-agent bt-discoverable
}

disable_power_saving() {
  apt-get install -y --no-install-recommends iw iputils-arping

  # a napping wifi radio misses broadcast ARP/mDNS - the Pi "disappears"
  # from devices whose cache expired while unicast traffic keeps working
  printf "[connection]\nwifi.powersave = 2\n" > /etc/NetworkManager/conf.d/wifi-powersave.conf
  iw dev wlan0 set power_save off 2>/dev/null || true

  # the in-firmware WPA supplicant mishandles the AP group-key rekey, after
  # which the chip cannot decrypt broadcast/multicast at all (unicast fine);
  # disable it and firmware roaming - same line newer RPi packages ship
  printf "options brcmfmac roamoff=1 feature_disable=0x282000\n" > /etc/modprobe.d/brcmfmac.conf

  cat > /etc/systemd/system/cpu-performance.service <<'UNIT'
[Unit]
Description=Pin the CPU governor to performance

[Service]
Type=oneshot
ExecStart=/bin/sh -c "for g in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do echo performance > $g; done"

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now cpu-performance

  # the USB DAC must never be power-managed
  grep -q usbcore.autosuspend /boot/firmware/cmdline.txt \
    || sed -i "1s/$/ usbcore.autosuspend=-1/" /boot/firmware/cmdline.txt
}

install_net_announcer() {
  cat > /opt/pi-speakers/net-announce.sh <<'SCRIPT'
#!/bin/sh
# The Pi wifi firmware stops receiving broadcast frames (ARP requests,
# mDNS queries) hours after association - typically after the AP rekeys
# the group key. Unicast keeps working, so stay reachable by announcing:
# gratuitous ARP keeps every client cache warm, and a periodic avahi kick
# re-multicasts the mDNS records.
count=0
while true; do
  ip=$(ip -4 -o addr show wlan0 | awk '{print $4}' | cut -d/ -f1)
  [ -n "$ip" ] && arping -q -c 1 -U -I wlan0 "$ip"
  count=$((count + 1))
  [ $((count % 30)) -eq 0 ] && systemctl try-reload-or-restart avahi-daemon
  sleep 10
done
SCRIPT
  chmod 755 /opt/pi-speakers/net-announce.sh

  cat > /etc/systemd/system/pi-speakers-net-announce.service <<'UNIT'
[Unit]
Description=Pi Speakers network presence announcer
After=network-online.target

[Service]
ExecStart=/bin/sh /opt/pi-speakers/net-announce.sh
Restart=always

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now pi-speakers-net-announce
}

pin_dac_level() {
  [ "$AUDIO_CARD" = "Creation" ] || return 0

  # alsactl restores mixer state before the USB DAC enumerates, so the card
  # boots at whatever it last saved; the DAC is meant to sit at full scale
  # (gain staging: the speaker knob is the ceiling), so pin it once it appears
  cat > /etc/systemd/system/pi-speakers-dac-level.service <<'UNIT'
[Unit]
Description=Pin the USB DAC hardware level to full scale
After=sound.target

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'for i in $(seq 1 30); do amixer -q -c Creation sset Speaker 100% unmute && exit 0; sleep 1; done; exit 1'

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now pi-speakers-dac-level
}

install_packages
write_alsa_config
seed_eq_state
verify_pipeline
configure_shairport
install_spotify_connect
setup_bluetooth
disable_power_saving
install_net_announcer
pin_dac_level

echo "Stage 2 done: EQ pipeline + Spotify Connect + Bluetooth active"
